name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.4'
        enable-stack: true
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('**/package.yaml') }}-stack
    - name: Build
      run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    - name: Run tests
      run: stack test --system-ghc
